### ISSUE TITLE
check db files ryon provided to look for 2002 data

### ISSUE THREAD

**Issue by alvizek** [FlowWest/feather-mini-snorkel#7]
We are missing 2002 data from this dataset. Ryon provided some potential db files here to check:

https://netorg629193.sharepoint.com/:f:/s/VA-FeatherRiver/EnFDn9gI00lLuQ_L_5OX_iYBkoRrCKcEvbwkc7uriUDRbA?e=7tplSu

**Comment by MaddeeRubenson** [comment]
The `minisnorkdb3.mdb` that Ryon shared includes 2022 data. Exploring further.

**Comment by MaddeeRubenson** [comment]
Pull Request here: https://github.com/FlowWest/feather-mini-snorkel/pull/8
